### PR TITLE
Add fix and test for MetricsSystem.prometheus()

### LINKED ISSUE #48: Getting prometheusFactoryNotBootstrapped
I am trying to use this in my Vapor 4 app. I have followed the Readme and I'm bootstrapping PrometheusClient in the main `configure(_ app: Application)` method, like this:

```
let myPrometheus = PrometheusClient()
MetricsSystem.bootstrap(PrometheusMetricsFactory(client: myPrometheus))
```

And for the /metrics route, I am using the basic implementation too:
```
app.get("metrics") { request -> EventLoopFuture<String> in
        let promise = request.eventLoop.makePromise(of: String.self)
        DispatchQueue.global().async {
            do {
                try MetricsSystem.prometheus().collect(into: promise)
            } catch {
                promise.fail(error)
            }
        }
        return promise.futureResult
    }
```

But when I try accessing /metrics in the web browser, I get the following error:

> [ WARNING ] prometheusFactoryNotBootstrapped(bootstrappedWith: "PrometheusMetricsFactory(client: Prometheus.PrometheusClient, configuration: Prometheus.PrometheusMetricsFactory.Configuration(labelSanitizer: Prometheus.PrometheusLabelSanitizer(allowedCharacters: \"abcdefghijklmnopqrstuvwxyz0123456789_:\"), timerImplementation: Prometheus.PrometheusMetricsFactory.TimerImplementation(_wrapped: Prometheus.PrometheusMetricsFactory.TimerImplementation._Wrapped.summary(defaultQuantiles: [0.01, 0.05, 0.5, 0.9, 0.95, 0.99, 0.999])), defaultRecorderBuckets: Prometheus.Buckets(buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 1.7976931348623157e+308])))") [request-id: 1704CFC1-E848-41E3-992A-7DB5CA7B1C0F]

Any help with this would be much appreciated 🙏. And thank you for creating this package!

### PR DESCRIPTION
**Pull request by MrLotU**
Fixes #48 

SwiftPrometheus 1.0.0 Alpha 10 introduced a bug where `MetricsSystem.prometheus()` would no longer work, since it looks for a `PrometheusClient` instance, but since Alpha 10 it's a wrapper struct.

Introduced new with this PR is a `PrometheusWrappedMetricsFactory` protocol that should be used by any `MetricsFactory` wrapping `PrometheusClient` in any way.

`MetricsSystem.prometheus()` will now look for a `PrometheusWrappedMetricsFactory` and return the underlying `client`

### Checklist
- [x] The provided tests still run.
- [x] I've created new tests where needed.
- [x] I've updated the documentation if necessary.

### CODE REVIEW

File: Tests/SwiftPrometheusTests/PrometheusMetricsTests.swift [hunk 1]
```diff
@@ -21,6 +21,13 @@ final class PrometheusMetricsTests: XCTestCase {
         self.prom = nil
         try! self.group.syncShutdownGracefully()
     }
+
+    func testGetPrometheus() {
+        MetricsSystem.bootstrapInternal(NOOPMetricsHandler.instance)
+        XCTAssertThrowsError(try MetricsSystem.prometheus())
+        MetricsSystem.bootstrapInternal(PrometheusMetricsFactory(client: self.prom))
```
Comment (ktoso) [inline Tests/SwiftPrometheusTests/PrometheusMetricsTests.swift:28]: Not sure I love that style but I guess this was introduced some time recently for some reason?

**Review by ktoso — APPROVED** [review]
Looks fine to me, thanks for the ping!

Why do we do the extra dance with the factory wrapper `(of:` nowadays? AFAIR originally we'd just bootstrap with the client itself right?

File: Tests/SwiftPrometheusTests/PrometheusMetricsTests.swift (hunk 1 above)
Comment (MrLotU) [reply Tests/SwiftPrometheusTests/PrometheusMetricsTests.swift:28]: Yeah, see #46 and #44 for full context.

Using `PrometheusClient` directly limited some options :)

Comment (ktoso) [reply Tests/SwiftPrometheusTests/PrometheusMetricsTests.swift:28]: I see, so it's for the configs etc. Thanks for the pointer; perhaps we can sugar the configuration-less case to just bootstrap with prometheus client as parameter but that's minor...

Thanks for the pointer :)

Comment (MrLotU) [reply Tests/SwiftPrometheusTests/PrometheusMetricsTests.swift:28]: No problem. And definitely open to add sugar here 👍🏻
